name: Rust lint

on:
    push:
      branches: [main, dev]
    pull_request:
      branches: ["**"]

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust_lint:
    defaults:
      run:
        working-directory: ./src-tauri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          workspaces: "./src-tauri -> target"
          key: rust-cache
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev patchelf
      - name: Run Clippy
        run: |
          mkdir ../dist
          cargo clippy --workspace --all-targets --all-features
