name: Rust lint

on:
    push:
      branches: [main, dev]
    pull_request:
      branches: ["**"]

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  rust_lint:
    defaults:
      run:
        working-directory: ./src-tauri
    runs-on: ubuntu-22.04
    steps:
      - name: Install minimal stable
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
          key: rust-cache
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Run Clippy
        run: |
          mkdir ../dist
          cargo clippy --workspace --all-targets --all-features